## Downloading Dataset from Kaggle

In [1]:
# import kagglehub

# path = kagglehub.dataset_download("endofnight17j03/imdb-movies-review")

# print("Path to dataset files:", path)

## Imports

In [2]:
import pandas as pd
# import string
# import nltk
# from nltk.tokenize import word_tokenize
# from nltk.corpus import stopwords, wordnet
# from nltk.stem import WordNetLemmatizer

# nltk.download('punkt')
# nltk.download('stopwords')
# nltk.download('wordnet')
# nltk.download('averaged_perceptron_tagger')

## 1. Data Pre-processing

In [3]:
# Loading Dataset
df = pd.read_csv(r"./dataset/IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
# Filtering Dataset
df['review'] = df['review'].str.replace("<br />", "")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. The filming tec...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
# Formatting Data
for cols in df.columns:
    df[cols] = df[cols].str.lower()

df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [6]:
# # Tokenization
# df['tokens'] = df['review'].apply(word_tokenize)
# df['tokens']

In [7]:
# # Filtering Tokens
# punctuation = set(string.punctuation)
# stop_words = set(stopwords.words('english'))

# filter_set = stop_words.union(punctuation)

# def filter_tokens(tkn):
#     filtered_words = [word for word in tkn if word not in filter_set and word.isalpha()]
#     return filtered_words

# df["filtered_tokens"] = df["tokens"].apply(filter_tokens)
# df["filtered_tokens"].head()

In [8]:
# # Lemmatization
# lemmatizer = WordNetLemmatizer()

# def get_wordnet_pos(tag):
#     if tag.startswith('J'):
#         return wordnet.ADJ
#     elif tag.startswith('V'):
#         return wordnet.VERB
#     elif tag.startswith('N'):
#         return wordnet.NOUN
#     elif tag.startswith('R'):
#         return wordnet.ADV
#     else:
#         return wordnet.NOUN
    
# def lemmatize_tokens(tkns):
#     pos_tags = nltk.pos_tag(tkns)
#     lemmatized_words = []
    
#     for word, tag in pos_tags:
#         wntag = get_wordnet_pos(tag)
#         lemma = lemmatizer.lemmatize(word, wntag)
#         lemmatized_words.append(lemma)
    
#     return lemmatized_words

# df["lemmatized_tokens"] = df["filtered_tokens"].apply(lemmatize_tokens)
# df["lemmatized_tokens"].head()

## Saving Processed Dataset

In [9]:
# # Dropping unwanted columns
# df.drop(columns=['tokens', 'filtered_tokens'], inplace=True)
# df.head()

In [10]:
df.to_csv(r"./dataset/processed_dataset.csv", index=False)